baseURL = ""
languageCode = "fr-fr"
title = "Mini FM transmitter"
theme = "hugo-classic"

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Guide"
    url = "/guide/"
    weight = 2
  [[menu.main]]
    name = "DÃ©tails techniques"
    url = "/techniques/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
